export const JOB_SCRAP_MASTER_DEFAULTS = [
  { category: 'job_title', value: 'Software Engineer', label: 'Software Engineer', sortOrder: 1 },
  { category: 'job_title', value: 'Senior Software Engineer', label: 'Senior Software Engineer', sortOrder: 2 },
  { category: 'job_title', value: 'Frontend Developer', label: 'Frontend Developer', sortOrder: 3 },
  { category: 'job_title', value: 'React Developer', label: 'React Developer', sortOrder: 4 },
  { category: 'job_title', value: 'Full Stack Developer', label: 'Full Stack Developer', sortOrder: 5 },
  { category: 'job_title', value: 'Backend Developer', label: 'Backend Developer', sortOrder: 6 },
  { category: 'job_title', value: 'Java Developer', label: 'Java Developer', sortOrder: 7 },
  { category: 'job_title', value: 'Python Developer', label: 'Python Developer', sortOrder: 8 },
  { category: 'job_title', value: 'Data Engineer', label: 'Data Engineer', sortOrder: 9 },
  { category: 'job_title', value: 'DevOps Engineer', label: 'DevOps Engineer', sortOrder: 10 },
  { category: 'job_title', value: 'Cloud Engineer', label: 'Cloud Engineer', sortOrder: 11 },
  { category: 'job_title', value: 'QA Engineer', label: 'QA Engineer', sortOrder: 12 },
  { category: 'job_title', value: 'Business Analyst', label: 'Business Analyst', sortOrder: 13 },
  { category: 'job_title', value: 'Product Manager', label: 'Product Manager', sortOrder: 14 },
  { category: 'country_code', value: 'US', label: 'United States (US)', sortOrder: 1 },
  { category: 'country_code', value: 'IN', label: 'India (IN)', sortOrder: 2 },
  { category: 'country_code', value: 'GB', label: 'United Kingdom (GB)', sortOrder: 3 },
  { category: 'country_code', value: 'CA', label: 'Canada (CA)', sortOrder: 4 },
  { category: 'country_code', value: 'AU', label: 'Australia (AU)', sortOrder: 5 },
  { category: 'country_code', value: 'DE', label: 'Germany (DE)', sortOrder: 6 },
  { category: 'country_code', value: 'SG', label: 'Singapore (SG)', sortOrder: 7 },
  { category: 'domain', value: 'greenhouse.io', label: 'Greenhouse', sortOrder: 1 },
  { category: 'domain', value: 'lever.co', label: 'Lever', sortOrder: 2 },
  { category: 'domain', value: 'ashbyhq.com', label: 'Ashby', sortOrder: 3 },
  { category: 'domain', value: 'workday.com', label: 'Workday', sortOrder: 4 },
  { category: 'domain', value: 'myworkdayjobs.com', label: 'Workday Jobs', sortOrder: 5 },
  { category: 'domain', value: 'icims.com', label: 'iCIMS', sortOrder: 6 },
  { category: 'domain', value: 'smartrecruiters.com', label: 'SmartRecruiters', sortOrder: 7 },
  { category: 'domain', value: 'jobs.jobvite.com', label: 'Jobvite', sortOrder: 8 },
];
